### ISSUE TITLE
Screencasts for build-testcase-*

### ISSUE THREAD

**Issue by gm3dmo** [gm3dmo/the-power#188]
Provide screencasts to accompany testcase scripts.

```[tasklist]
### Tasks
- [x] [build-testcase](https://www.youtube.com/watch?v=yB55AVjM7DY&t=1s)
- [x] build-testcase-workflow-simple
- [x] build-testcase-with-commit-status
```
